#Default Replica Count for all deployments
replicaCount: 1

#Resources values
resources:
  requests:
    memory: "128Mi"
    cpu: "250m"
  limits:
    memory: "256Mi"
    cpu: "500m"

#service values
service:
  type: ClusterIP
  port: 80

#HPA Values
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 30


