apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-web
  template:
    metadata:
      labels:
        app: go-web
    spec:
      containers:
        - name: go-web
          image: 'rt007/go-web:latest'
          ports:
            - name: server
              containerPort: 8080
          resources:
            requests:
              memory: 256M
              cpu: '0.25'
            limits:
              memory: 512M
              cpu: '0.5'
---
apiVersion: v1
kind: Service
metadata:
  name: go-web-service
spec:
  selector:
    app: go-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
